### ISSUE TITLE
NonUST strategies lose value with swap fees

### ISSUE THREAD

**Issue by code423n4** [code-423n4/2022-01-sandclock-findings#137]
# Handle

cmichel

# Vulnerability details

The `NonUSTStrategy` swaps the underlying to UST using Curve on each deposit and withdrawal.
This swap comes with fees and leads to users immediately losing value on their deposit (if they were to withdraw the shares again in the same block).

## Impact
In theory, admins could withdraw from the vault and invest in the vault many times to completely burn the funds in the strategy by paying fees each time.

## Recommended Mitigation Steps
Not sure what a good solution is. Depositing the underlying to a lending protocol and borrowing UST instead of swapping would eliminate the fee issue.
As long as the anchor yield is higher than the borrow rate this should not incur losses but the yield would be a lot lower due to having to over-collateralize the UST.

**Comment by naps62** [comment]
Fixed in https://github.com/lindy-labs/sc_solidity-contracts/pull/69
