### ISSUE TITLE
[WP-L6] Critical operations should emit events

### ISSUE THREAD

**Issue by code423n4** [code-423n4/2022-01-sandclock-findings#162]
# Handle

WatchPug

# Vulnerability details

Across the contracts, there are certain critical operations that change critical values that affect the users of the protocol.

It's a best practice for these setter functions to emit events to record these changes on-chain for off-chain monitors/tools/interfaces to register the updates and react if necessary.

Instances include:

https://github.com/code-423n4/2022-01-sandclock/blob/a90ad3824955327597be00bb0bd183a9c228a4fb/sandclock/contracts/Vault.sol#L103-L119

```solidity
function setStrategy(address _strategy)
    external
    override(IVault)
    requiresTrust
{
    require(_strategy != address(0), "Vault: strategy 0x");
    require(
        IStrategy(_strategy).vault() == address(this),
        "Vault: invalid vault"
    );
    require(
        address(strategy) == address(0) || strategy.investedAssets() == 0,
        "Vault: strategy has invested funds"
    );

    strategy = IStrategy(_strategy);
}
```

**Comment by naps62** [comment]
@gabrielpoca I'm not sure if this solved already?

**Comment by naps62** [comment]
Confirmed. seems to be fixed now
