### ISSUE TITLE
Inconvenient retrieval of depositors token IDs

### ISSUE THREAD

**Issue by code423n4** [code-423n4/2022-01-sandclock-findings#73]
# Handle

kenzo

# Vulnerability details

From a smart contract, it is inconvenient (if not impossible) to retrieve depositor token IDs in order to issue a withdrawal from a vault.

When making a deposit, the token IDs are emitted in logs, but not returned from the function.
Also, Depositors has no function that returns all deposits of an address.

## Impact
Can be inconvenient to retrieve and withdraw deposits. 
However, I understand that this can be a design decision.

## Recommended Mitigation Steps
- Consider returning deposit token ids from deposit function
- Consider adding a function to retrieve all deposits of address (eg. using ERC721Enumerable)

**Comment by assafom** [comment]
If you return the the IDs from the deposit function, another contract could still use it in the midst of a transaction.

So for example you can imagine a MasterChef/staking contract that deposits on Sandclock on behalf of a user. If you return the deposit IDs, the staking contract could save them and later withdraw them.
But without returning the IDs such staking contract is not possible without backend (AFAIK/R).

**Comment by naps62** [comment]
@assafom that's a fair point. I guess the reason I didn't consider it is because we're not aiming for those use cases, but only for EOAs (this is a product decision though, not related to the contracts)

I'll reopen this and reconsider

**Comment by naps62** [comment]
Fixed in https://github.com/sandclock-org/solidity_contracts/pull/34
